### PR TITLE
threddsConfig xml error in commented xml

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
This change is [Reviewable](https://reviewable.io/reviews/unidata/tds/224)

### CODE REVIEW

**Review by haileyajohnson — APPROVED** [review]

**Comment by haileyajohnson** [comment]
@dblodgett-usgs thanks for the fix! Would you mind signing the CLA? Then I can merge this in :)

**Comment by haileyajohnson** [comment]
@dblodgett-usgs thanks for the fix! Would you mind signing the CLA? Then I can merge this in :)

**Comment by haileyajohnson** [comment]
Weird, me too... it was working last week. I'll ask around and force merge if we can't get it working. Thanks!

**Comment by dopplershift** [comment]
@dblodgett-usgs I think it's just being [slow lately](https://github.com/cla-assistant/cla-assistant/issues/874). I know it's suboptimal, but if you wait long enough I think it will load? It did just for me anyway.

**Pull request merged**
