### PR TITLE
Change github action to refer to TDS, not netCDF-Java

### PR DESCRIPTION
**Pull request by lesserwhirls**
This change is [Reviewable](https://reviewable.io/reviews/unidata/tds/166)

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Also, we were checking code style in two workflows...oops, that's my bad.

**Comment by haileyajohnson** [comment]
> Looks like it might be having issues reading the dtd?

Related to namespace/schemas migration, @oxelson ?

**Comment by lesserwhirls** [comment]
~~~
    [19:16:41.672 WARN  serverStartup] Cannot parse wmsConfig.xml:
    [19:16:41.672 WARN  serverStartup] Error on line 1 of document http://www.unidata.ucar.edu/schemas/thredds/dtd/ncwms/wmsConfig.dtd: The markup declarations contained or pointed to by the document type declaration must be well-formed.
~~~

I can dig some this evening. Smells like code that isn't handling the redirect properly.

**Comment by ethanrd** [comment]
Didn't we turn validation off for server configuration catalog files some time ago? The thinking was validation should be done when developing the files but not each time the server started.

**Comment by ethanrd** [comment]
Hi Sean @lesserwhirls - I think TDS logs show catalog config file parsing (and well-formed) errors/warnings but not schema validation errors. If I validate [tds/src/test/content/thredds/catalog.xml](https://github.com/Unidata/tds/blob/main/tds/src/test/content/thredds/catalog.xml), I get an error on [line 243](https://github.com/Unidata/tds/blob/1430fe263a385d18c585cc5bc8f9ccd895e87a66/tds/src/test/content/thredds/catalog.xml#L243). Evidently, according to the schema, the `datasetRoot` element on that line should be before any `dataset` or `datasetScan` elements. When I run a TDS using tds/src/test/content/thredds/ for the content root, there is no complaint in the `catalogInit.log` file.

Anyway, I mentioned this because it had me leaning towards your “not validate” option, or both really (i.e., also update DTD location URL).

**Comment by lesserwhirls** [comment]
I see. I've updated the PR to turn off the validation in addition to updating the DTD location.

There will still need to be an email sent out to the THREDDS list giving people the heads-up that they need to update the URL of the DTD. I believe this will be the case for both `4.x` and `5.x` servers.

**Comment by oxelson** [comment]
Yes, I believe it is.

**Pull request merged**
