### PR TITLE
Changes to NetcdfFormatWriter.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Misc deprecation fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/tds/91)

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Failure seems to be:

2020-06-17T18:16:33.2053793Z Failed to get resource: GET. [HTTP HTTP/1.1 504 Gateway Time-out: https://jcenter.bintray.com/org/springframework/spring-jcl/5.2.6.RELEASE/spring-jcl-5.2.6.RELEASE.jar]

**Comment by lesserwhirls** [comment]
I restarted, but got a new error, and an error on the one that had passed before :-/ Let me see what's up...

**Comment by lesserwhirls** [comment]
It'll also need rebased

**Comment by lesserwhirls** [comment]
...hmmm...

_Can't pass the tests if you don't build with the upstream fixes_

I deployed new netCDF-Java snapshots, and now we're good when we run the tests with builders on, but not with the builders off (so the failure mode switched). I think I know what's up there.

**Comment by JohnLCaron** [comment]
rebased

**Comment by lesserwhirls** [comment]
Ok, so here is what I know. There is a file in this repo (`<tds-repo>/dap4/d4tests/src/test/data/resources/testfiles/test_groups1.nc`) with the following structure:

~~~
netcdf dap4/d4tests/src/test/data/resources/testfiles/test_groups1.nc {
  dimensions:
    dim1 = 5;
  group: g {
    dimensions:
      dim2 = 3;
    group: h {
      dimensions:
        dim3 = 7;
      variables:
        int v1(dim1=5);
        float v2(dim2=3);
    }
    group: i {
      dimensions:
        dim3 = 7;
      variables:
        int v1(dim1=5);
        float v3(dim3=7);
    }
  }
  // global attributes:
}
~~~

It looks like the test is failing on this fail with this error:

~~~
17:58:26.950 [Test worker] ERROR SYSERR - Testcase: c:/Users/sarms/dev/unidata/repos/thredds/tds/dap4/d4tests/src/test/data/resources/testfiles/test_groups1.nc
17:58:26.950 [Test worker] ERROR SYSERR - Baseline: c:/Users/sarms/dev/unidata/repos/thredds/tds/dap4/d4tests/src/test/data/resources/TestServlet/baseline/test_groups1.nc
17:58:26.987 [Test worker] ERROR SYSERR - DMR Comparison
17:58:26.991 [Test worker] ERROR SYSERR - >>>> 26 CHANGED FROM
                <Dim name="/g/i/dim3"/>
>>>>     CHANGED TO
                <Dim name="/g/h/dim3"/>
>>>> Dap4 Testing: End of differences.
~~~

But, the failure isn't consistent. I can run the tests multiple times in a row, and sometimes is passes, sometimes is doesn't. I'm not recompiling in-between, I just run the test, watch it fail, run it again, watch it pass, run it 10 more times, watch it fail, and once more, then it passes. It's not deterministic, at least on my machine. I think that's why sometimes it's the run that uses the new builder stuff that fails, and sometimes it's not (and just like this last rerun of the tests, both failed).

This seems to indicate that sometimes, somewhere, the code is finding `dim3` from group `g/i`, and sometimes it finds `dim3` from group `g/h`. Any of this triggering some ideas on what could be going on?

**Comment by lesserwhirls** [comment]
I rebased this one and fixed github actions over on Unidata/tds#97. Sorry it took so long to get this one in.

**Pull request closed without merging**
