### PR TITLE
Initial UGRID support at the NetcdfDataset level

### PR DESCRIPTION
**Pull request by lesserwhirls**
Ok, this is a big one, but it's a minimum testable implementation of coordinate system support for UGRIDs. First off, the UGRID code is only used in the TDS version of toolsUI, and not in the TDS itself (that is, no risk to breaking the TDS with this PR). This PR incorporates code from 2011-2014 from Applied Science Associates (via Kyle Wilcox). The code was then updated to use the new netCDF-Java builder API and to use the `CFSubConvention` service provider mechanism. Finally, I added tests for `NetcdfDataset` level functionality.

Notes: I ran into a bug related to coordinate system builders when using NcML to wrap an existing dataset to provide the `Conventions` attribute, which I will fix next in netCDF-Java. Finally, 

Next Steps for NOAA IOOS project: I'll likely need to make a few changes in the way the current FMRC code checks lat/lon variables, but after that, the TDS should be able to create FMRCs out of UGRID collections. At that point, we'll have a version of the TDS that we can use for NOAA testing. It won't include NCSS support, but that isn't supported on their files at this point anyways, but we will match the current capabilities they have on UGRID files (so, yeah, ready for testing to replace their current NcML aggregations with FMRCs). I'll begin work on NCSS support once we get FMRC support.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/tds/260)

### CODE REVIEW

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/260)* status: all files reviewed, 4 unresolved discussions (waiting on @lesserwhirls)

___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java` line 308 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_NCKx56KtZemD2jmd:-N8_NCKx56KtZemD2jme:berggbn) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java#L308)):*
> ```Java
>          * Z
>          */
>         if (cs.hasVerticalAxis()) {
> ```

Can we reduce the number of calls to `cs.getZAxis()`, `getLatAxis()`, etc in this block by saving the first result?
___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java` line 515 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_O74CAmLJQFCc0tfA:-N8_O74D43x5u48mbQJm:b-ttzi7q) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java#L515)):*
> ```Java
>     } catch (IOException e) {
>       System.out.println(e);
>     }
> ```

logger?
___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java` line 155 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_PCYx3yLb0TZcNkew:-N8_PCYx3yLb0TZcNkex:be7fkkc) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java#L155)):*
> ```Java
>     for (UGridDatatype m : meshVariables) {
>       if (m.getName().equals(name)) {
>         z = m;
> ```

Can this just break or return when the the right variable is found?
___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java` line 503 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_PpKaE5KT5zXgHKyN:-N8_PpKaE5KT5zXgHKyO:buo9nmt) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java#L503)):*
> ```Java
>       for (UGridDatatype m : meshVariables) {
>         if (m.getName().equals(name)) {
>           z = m;
> ```

Same here

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/260)* status: 41 of 45 files reviewed, 4 unresolved discussions (waiting on @haileyajohnson)

___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java` line 308 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_NCKx56KtZemD2jmd:-N8t0uT8-LRdmA3Ufz2r:b-896fix) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java#L308)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Can we reduce the number of calls to `cs.getZAxis()`, `getLatAxis()`, etc in this block by saving the first result?
</blockquote></details>

Done.
___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java` line 515 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_O74CAmLJQFCc0tfA:-N8t0wX046kZtjk7CTsT:b-cdfzeq) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/MeshVariable.java#L515)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

logger?
</blockquote></details>

Done. Snagged a few other System.out.prinln usages while I was at it.
___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java` line 155 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_PCYx3yLb0TZcNkew:-N8t16cY5M_wuvJctYgJ:b-896fix) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java#L155)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Can this just break or return when the the right variable is found?
</blockquote></details>

Done.
___
*[`tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java` line 503 at r1](https://reviewable.io/reviews/unidata/tds/260#-N8_PpKaE5KT5zXgHKyN:-N8t17xg8XB4adesM7OC:b-896fix) ([raw file](https://github.com/unidata/tds/blob/7ad37a437307170a37d53a8d613d7ab59a9b2b89/tds-ugrid/src/main/java/ucar/nc2/dt/ugrid/UGridDataset.java#L503)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

**Comment by lesserwhirls** [comment]
Thanks for the feedback @haileyajohnson! I have not been through the UGRID code with a fine-toothed comb yet. I was wanting to get a few tests in place before any major reconstruction, but these were good to catch now rather than later.

**Comment by lesserwhirls** [comment]
If these changes look good, I'll rebase.

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/260)* status: all files reviewed, 4 unresolved discussions (waiting on @haileyajohnson)

**Pull request merged**
