### PR TITLE
Update how FileServer determines content-type

### PR DESCRIPTION
**Pull request by ethanrd**
Start by querying the server for well known and server configured content types.
If still unknown, check for TDS specific content types.

Addresses issue #161.

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/tds/163)

### CODE REVIEW

**Comment by ethanrd** [comment]
@haileyajohnson - Oops! Yup, I'll switch to use ContentType.png. And get spotless fixed.

Ugh! Spotless makes that enum very hard to read. Didn't realize it was so strict about line length that it doesn't allow shorter lines.

**Comment by haileyajohnson** [comment]
> @haileyajohnson - Oops! Yup, I'll switch to use ContentType.png. And get spotless fixed.
> 
> Ugh! Spotless makes that enum very hard to read. Didn't realize it was so strict about line length that it doesn't allow shorter lines.

Hmm, I don't like that either... let me see if I can create an exception for enums somehow

**Comment by haileyajohnson** [comment]
Ok, I think I got it thanks to a lot of other people on google having this problem. See #164 . I can either push the change separately and you have rebase, or you can just copy the change to the style guidelines into this PR and I can close #164.

**Comment by ethanrd** [comment]
Nice. OK. I'll copy your changes in and get this all cleaned up. Thanks @haileyajohnson!

**Pull request merged**
