### PR TITLE
Lay groundwork for next beta release

### PR DESCRIPTION
**Pull request by lesserwhirls**
* Upgrade to netCDF-Java 5.4.2 release
* Fix a few tests
* Upgrade to latest gradle (`6.9.1`)
* Do some documentation work (service related docs in the admin guide)

Once merged, I will begin the release process for `5.0.0-beta9` (the last, super final, mega ultimate beta)

---
This change is [Reviewable](https://reviewable.io/reviews/unidata/tds/148)

### CODE REVIEW

**Review by haileyajohnson — COMMENTED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/148)* status: all files reviewed, 1 unresolved discussion (waiting on @lesserwhirls)

___
*[docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md, line 18 at r1](https://reviewable.io/reviews/unidata/tds/148#-MiRw4PU4d9iQC6zLBIn:-MiRw4PU4d9iQC6zLBIo:b-j2wdlf) ([raw file](https://github.com/unidata/tds/blob/d284c67001e3f812abafa04e95e09a2e77180ef5/docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md#L18)):*
> ```Markdown
> ## Enabling NCSS In the TDS
> 
> The NetCDF Subset Service must be enabled by default.
> ```

"is enabled by default"?

**Review by lesserwhirls — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/148)* status: all files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

___
*[docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md, line 18 at r1](https://reviewable.io/reviews/unidata/tds/148#-MiRw4PU4d9iQC6zLBIn:-MiRzE912kP4M40wecko:b-h55kcd) ([raw file](https://github.com/unidata/tds/blob/d284c67001e3f812abafa04e95e09a2e77180ef5/docs/adminguide/src/site/pages/tds_tutorial/tds_configuration/AddingNcss.md#L18)):*
<details><summary><i>Previously, haileyajohnson wrote…</i></summary><blockquote>

"is enabled by default"?
</blockquote></details>

Insert `sad_trombone.wav` here...

sad trombone

**Comment by lesserwhirls** [comment]
Should be good now.

**Review by haileyajohnson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/148)* status: all files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

**Pull request merged**
